<#
.SYNOPSIS
    Install winlinux as global commands usable from PowerShell / cmd.

.DESCRIPTION
    Copies winlinux.exe into a user bin dir and generates .cmd shims for common
    Linux commands (ls, grep, cat, ...) that forward to Git Bash's GNU tools.
    Adds the bin dir to the current user's PATH (no administrator required).

.EXAMPLE
    .\install.ps1
.EXAMPLE
    .\install.ps1 -GitRoot "D:\Git" -Force
#>
param(
    [string]$GitRoot = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Find-GitRoot {
    param([string]$Hint)
    $roots = @()
    if ($Hint) { $roots += $Hint }
    $roots += @(
        "C:\Program Files\Git",
        "C:\Program Files (x86)\Git",
        "D:\Git",
        "E:\Git",
        "C:\Git"
    )
    foreach ($r in $roots) {
        $bash = Join-Path $r "usr\bin\bash.exe"
        $ls = Join-Path $r "usr\bin\ls.exe"
        if ((Test-Path $bash) -and (Test-Path $ls)) {
            return $r
        }
    }
    return $null
}

$gitRoot = Find-GitRoot $GitRoot
if (-not $gitRoot) {
    throw "Git Bash not found. Install Git for Windows, or pass -GitRoot."
}
$bash = Join-Path $gitRoot "bin\bash.exe"
if (-not (Test-Path $bash)) { $bash = Join-Path $gitRoot "usr\bin\bash.exe" }
$bashUnix = $bash -replace '\\', '/'

$binDir = Join-Path $env:LOCALAPPDATA "winlinux\bin"
New-Item -ItemType Directory -Force -Path $binDir | Out-Null

# 1. Install winlinux.exe
$exe = Join-Path $PSScriptRoot "build-release\winlinux.exe"
if (-not (Test-Path $exe)) {
    $exe = Join-Path $PSScriptRoot "build-debug\winlinux.exe"
}
if (-not (Test-Path $exe)) {
    throw "winlinux.exe not built yet. Run .\build.ps1 first."
}
Copy-Item -LiteralPath $exe -Destination $binDir -Force

# 2. Generate GNU command shims
$bashPath = $bash
$tools = @(
    "ls", "cat", "grep", "sed", "awk", "find", "wc", "head", "tail",
    "sort", "uniq", "cut", "tr", "paste", "join", "tee", "xargs", "printf",
    "echo", "touch", "rm", "cp", "mv", "mkdir", "rmdir", "chmod", "chown",
    "chgrp", "ln", "realpath", "readlink", "basename", "dirname", "stat",
    "date", "cal", "whoami", "hostname", "uname", "uptime", "ps", "top",
    "kill", "pwd", "which", "whereis", "type", "seq", "factor",
    "expr", "test", "sleep", "time", "tar", "gzip", "gunzip", "zcat",
    "bzip2", "unzip", "zip", "file", "comm", "diff", "patch", "cmp",
    "strings", "od", "hexdump", "less", "more", "nl", "pr", "fold",
    "expand", "unexpand", "tac", "rev", "yes", "md5sum",
    "sha1sum", "sha256sum", "cksum", "env", "printenv", "locale",
    "du", "df", "mount", "id", "groups", "users", "w", "ping",
    "nc", "ssh"
) | Select-Object -Unique

function New-Shim {
    param($tool)
    $shm = Join-Path $binDir "$tool.cmd"
    $content = "@echo off`r`n" +
        "rem Generated by winlinux install.ps1`r`n" +
        "`"$bashPath`" -lc `"`"$tool`" `"`$@`"`" -- %*`r`n" +
        "exit /b %errorlevel%`r`n"
    Set-Content -LiteralPath $shm -Value $content -Encoding ASCII -NoNewline
}

foreach ($t in $tools) {
    New-Shim $t
}

# 3. Add bin dir to user PATH if missing
$userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
$entries = $userPath -split ';' | Where-Object { $_ -ne "" }
if ($entries -notcontains $binDir) {
    $newPath = ($entries + $binDir) -join ';'
    [System.Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    Write-Host "Added to user PATH: $binDir"
} else {
    Write-Host "Already in user PATH: $binDir"
}

Write-Host ""
Write-Host "Installed $(@($tools).Count) commands + winlinux to: $binDir"
Write-Host "Git Root : $gitRoot"
Write-Host "Restart your terminals, then use: ls, grep, cat, ... directly."
Write-Host "Or run: winlinux -c ""ls -la"""
